COMP_hack: DiffieHellman.cpp File Reference
DiffieHellman.cpp File Reference
Test the Diffie-Hellman key exchange.
#include <PushIgnore.h>
#include <gtest/gtest.h>
#include <PopIgnore.h>
#include <Log.h>
#include <TcpServer.h>
#include <TcpConnection.h>
Functions
void ExecTime (std::chrono::high_resolution_clock::time_point &t1, const libcomp::String &title="Time")
int main (int argc, char *argv[])
TEST (DiffieHellman, GenerateSaveLoad)
TEST (DiffieHellman, KeyExchange)
Detailed Description
Test the Diffie-Hellman key exchange.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2014-2016 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file DiffieHellman.cpp.
Function Documentation
void ExecTime (std::chrono::high_resolution_clock::time_point & t1, const libcomp::String & title = "Time") inline
Definition at line 76 of file DiffieHellman.cpp.
Referenced by TEST().
int main (int argc, char * argv[])
Definition at line 144 of file DiffieHellman.cpp.
TEST (DiffieHellman , GenerateSaveLoad)
Definition at line 37 of file DiffieHellman.cpp.
References libcomp::TcpServer::CopyDiffieHellman(), libcomp::TcpServer::GenerateDiffieHellman(), libcomp::TcpConnection::GetDiffieHellmanPrime(), libcomp::String::Length(), libcomp::TcpServer::LoadDiffieHellman(), and libcomp::TcpServer::SaveDiffieHellman().
TEST (DiffieHellman , KeyExchange)
Definition at line 84 of file DiffieHellman.cpp.
References libcomp::Log::AddStandardOutputHook(), ExecTime(), libcomp::TcpConnection::GenerateDiffieHellmanPublic(), libcomp::TcpConnection::GenerateDiffieHellmanSharedData(), libcomp::Log::GetSingletonPtr(), libcomp::String::Length(), and libcomp::TcpServer::LoadDiffieHellman().